### ISSUE TITLE
Era Filtering - Binary Laser Cannon

### ISSUE THREAD

**Issue by Moonsword22** [jdgwf/battletech-tools#20]
The binary laser cannon isn't listed in the Succession Wars list even though the weapon was introduced during that era (2812).

**Comment by Moonsword22** [comment]
Problem is `battlemech-creator-step5.js` is only looking at the era's start year but equipment introduced before its end year should logically be available.

I see where the problem is and how to fix it but have no ability to test changes.

**Comment by Moonsword22** [comment]
Tested first-stage change although there's some holes in the OR logic in there.  Equipment that goes extinct prior to the start of the era is listed, for instance.

**Comment by Moonsword22** [comment]
I'm not sure I've managed to properly eliminate the edge cases but this looks approximately correct. Era end should be used rather than era start as the boundary to catch equipment (re)introduced within the era, such as the blazer's introduction in the Succession Wars.

IF(
	reintro <= eraEnd
	||
	(
		intro <= eraEnd &&
		(
			extinct == 0
			|| extinct >= eraStart
		)
	)
)
{
	equipmentAvailable = true;
}

**Comment by jdgwf** [comment]
I have some code here for that: https://github.com/jdgwf/battletech-tools/blob/gh-pages/js/src/controllers/battlemech-creator-step5.js#L146

**Comment by Moonsword22** [comment]
Yeah, I was looking at that.  I see at least two bugs in the behaviors (listed below) and I'm pretty sure there are others but they're harder to spot.

- Weapons introduced within an era don't show up in that era's list (e.g., binary laser cannon in the Succession Wars, X-pulse lasers in the Clan Invasion).
- Weapons that go extinct will turn up in eras prior to their introduction (e.g., snub-nose PPC is listed in the Star League but it wasn't introduced until 2784).

I'll implement the logic pseudocoded above and test it tomorrow to see if it works.  Do you mind if I go ahead and set up the MUL eras [listed here](http://masterunitlist.info/Era/Index)?  The shorter time periods will make the testing simpler by exposing more of the edge cases.

**Comment by jdgwf** [comment]
> I'll implement the logic pseudocoded above and test it tomorrow to see if it works. Do you mind if I go ahead and set up the MUL eras listed here? The shorter time periods will make the testing simpler by exposing more of the edge cases.

I don't mind at all. I was originally trying to keep it more along the lines of the Tech Manual proper, however I did leave it open enough to add eras for this very reason. The eras were the least of my worries when I planned the data out.

The Record Sheet is my primary focus right now, and it's a doosey because I'd really like to have an SVG version so that I can bind events to it for an interactive Record Sheet like the Alpha Strike in play area(which I'd like to switch to SVG if possible too). I'd *much* rather not have to code the vector graphics in two different ways (one for interactive in-play, and one for pdf printing). This feature is one of the major development milestones and challenges.
