### ISSUE TITLE
Alpha Strike forcepack quick add adds the wrong or no mechs on some forcepacks

### ISSUE THREAD

**Issue by dwolkins** [jdgwf/battletech-tools#42]
When adding the Inner Sphere Battle Lance adds a Sneede and not a Rifleman RFL-3N.

Inner Sphere Command Lance does not add a Stinger to the current force.

Clan Elementals adds elemental sqd 3 and not sqd 5.

Clan Ad Hoc Star only adds the Hellion Prime and Fire Falcon Prime. It's missing the Kodiak, Pack Hunter, and Baboon.

Clan Striker Star doesn't add anything.

**Comment by cam-smith** [comment]
looks like the MUL has changed names on some units since this code was added.  See Sept 11, 2002, and June 6, 2022 entries at http://masterunitlist.info/Blog/Index.  Have a quick fix, but the rifleman is a bit harder, since when we lookup the "Rifleman RFL-3N" it's conflating it with the the sneed model that share that name

**Comment by cam-smith** [comment]
Fixed and Deployed
